### PR TITLE
Mint sign up mimick

### PR DESCRIPTION
**Pull request by jdmartinez1062**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Awesome work team :clap: 
Your project looks really nice :+1:.But we can make it even better :muscle: :smiley: 

[REQUIRED]
I notice the linter found some errors in your project, we need to fix them. Linting is important to reduce errors and improve the overall quality of your code.

[REQUIRED]
It's a good practice to also include the assignment link in the readme file along with the name of the contributors. If you need an example you can take a look at this [one](https://github.com/Torres-ssf/apple-site-clone/blob/master/README.md).

Please kindly make these changes and submit for code review again. Your project approval is very close :smiley: 
Happy coding

**Comment by jdmartinez1062** [comment]
@Ispirett, thanks for your feed back. As you requested, we tried to fix all the stickler issues, but we still have some like the universal selector issue and box-model, even though we are using border-box in the universal selector to avoid this. How should we address this?

**Comment by Oghenebrume50** [comment]
Reviewing....

**Pull request merged**
